export type SvnStatusCode = 'A' | 'M' | 'D' | 'R' | 'C' | 'X' | 'I' | '?' | '!' | '~'

export const STATUS_TEXT: Record<SvnStatusCode, string> = {
  A: 'svn.status.added',
  M: 'svn.status.modified',
  D: 'svn.status.deleted',
  R: 'svn.status.replaced',
  C: 'svn.status.conflicted',
  X: 'svn.status.external',
  I: 'svn.status.ignored',
  '?': 'svn.status.unversioned',
  '!': 'svn.status.missing',
  '~': 'svn.status.typeChanged',
}

export const STATUS_COLOR_CLASS_MAP = {
  A: 'text-green-600 dark:text-green-400',
  M: 'text-blue-600 dark:text-blue-400',
  D: 'text-red-600 dark:text-red-400',
  R: 'text-orange-500 dark:text-orange-300',
  C: 'text-purple-600 dark:text-purple-400',
  X: 'text-gray-600 dark:text-gray-400',
  I: 'text-yellow-700 dark:text-yellow-500',
  '?': 'text-gray-800 dark:text-gray-300',
  '!': 'text-rose-600 dark:text-rose-400',
  '~': 'text-indigo-600 dark:text-indigo-400',
}

export const FONT_SIZES = ['small', 'medium', 'large'] as const

export const FONT_FAMILIES = [
  'sans',
  'fira-sans',
  'inter',
  'jetbrains-mono',
  'lato',
  'noto-sans-jp',
  'nunito',
  'pt-sans',
  'quicksand',
  'roboto-condensed',
  'roboto-flex',
  'roboto',
  'rubik',
  'source-sans-3',
  'titillium-web',
  'ubuntu-condensed',
  'ubuntu',
  'urbanist',
] as const

export const THEMES = [
  'theme-default',
  'theme-nord',
  'theme-dracula',
  'theme-solarized',
  'theme-github',
  'theme-daylight',
  'theme-monokai',
  'theme-material',
  'theme-gruvbox',
  'theme-catppuccin',
  'theme-tokyo-night',
  'theme-rose-pine',
] as const

export const BUTTON_VARIANTS = ['default', 'secondary', 'destructive', 'outline', 'ghost', 'link'] as const

export const LANGUAGES = [
  { code: 'en', label: 'English' },
  { code: 'vi', label: 'Tiếng Việt' },
  { code: 'ja', label: '日本語' },
]

export const CATEGORY_DESCRIPTIONS: Record<string, string> = {
  BAD_PRACTICE: 'spotbugs.categoryDescriptions.badPractice',
  CORRECTNESS: 'spotbugs.categoryDescriptions.correctness',
  EXPERIMENTAL: 'spotbugs.categoryDescriptions.experimental',
  I18N: 'spotbugs.categoryDescriptions.i18N',
  MALICIOUS_CODE: 'spotbugs.categoryDescriptions.maliciousCode',
  MT_CORRECTNESS: 'spotbugs.categoryDescriptions.mtCorrectness',
  NOISE: 'spotbugs.categoryDescriptions.noise',
  PERFORMANCE: 'spotbugs.categoryDescriptions.performance',
  SECURITY: 'spotbugs.categoryDescriptions.security',
  STYLE: 'spotbugs.categoryDescriptions.style',
}

export const BUG_DESCRIPTIONS: Record<string, string> = {
  JUA_DONT_ASSERT_INSTANCEOF_IN_TESTS: 'spotbugs.bugDescriptions.jua_dont_assert_instanceof_in_tests',
  AA_ASSERTION_OF_ARGUMENTS: 'spotbugs.bugDescriptions.aa_assertion_of_arguments',
  CT_CONSTRUCTOR_THROW: 'spotbugs.bugDescriptions.ct_constructor_throw',
  CNT_ROUGH_CONSTANT_VALUE: 'spotbugs.bugDescriptions.cnt_rough_constant_value',
  NP_BOOLEAN_RETURN_NULL: 'spotbugs.bugDescriptions.np_boolean_return_null',
  SW_SWING_METHODS_INVOKED_IN_SWING_THREAD: 'spotbugs.bugDescriptions.sw_swing_methods_invoked_in_swing_thread',
  FI_FINALIZER_ONLY_NULLS_FIELDS: 'spotbugs.bugDescriptions.fi_finalizer_only_nulls_fields',
  FI_FINALIZER_NULLS_FIELDS: 'spotbugs.bugDescriptions.fi_finalizer_nulls_fields',
  UI_INHERITANCE_UNSAFE_GETRESOURCE: 'spotbugs.bugDescriptions.ui_inheritance_unsafe_getresource',
  AM_CREATES_EMPTY_ZIP_FILE_ENTRY: 'spotbugs.bugDescriptions.am_creates_empty_zip_file_entry',
  AM_CREATES_EMPTY_JAR_FILE_ENTRY: 'spotbugs.bugDescriptions.am_creates_empty_jar_file_entry',
  IMSE_DONT_CATCH_IMSE: 'spotbugs.bugDescriptions.imse_dont_catch_imse',
  CN_IMPLEMENTS_CLONE_BUT_NOT_CLONEABLE: 'spotbugs.bugDescriptions.cn_implements_clone_but_not_cloneable',
  CN_IDIOM: 'spotbugs.bugDescriptions.cn_idiom',
  CN_IDIOM_NO_SUPER_CALL: 'spotbugs.bugDescriptions.cn_idiom_no_super_call',
  DE_MIGHT_DROP: 'spotbugs.bugDescriptions.de_might_drop',
  DE_MIGHT_IGNORE: 'spotbugs.bugDescriptions.de_might_ignore',
  DM_EXIT: 'spotbugs.bugDescriptions.dm_exit',
  NM_FUTURE_KEYWORD_USED_AS_IDENTIFIER: 'spotbugs.bugDescriptions.nm_future_keyword_used_as_identifier',
  NM_FUTURE_KEYWORD_USED_AS_MEMBER_IDENTIFIER: 'spotbugs.bugDescriptions.nm_future_keyword_used_as_member_identifier',
  JCIP_FIELD_ISNT_FINAL_IN_IMMUTABLE_CLASS: 'spotbugs.bugDescriptions.jcip_field_isnt_final_in_immutable_class',
  DM_RUN_FINALIZERS_ON_EXIT: 'spotbugs.bugDescriptions.dm_run_finalizers_on_exit',
  NP_EQUALS_SHOULD_HANDLE_NULL_ARGUMENT: 'spotbugs.bugDescriptions.np_equals_should_handle_null_argument',
  FI_EMPTY: 'spotbugs.bugDescriptions.fi_empty',
  FI_NULLIFY_SUPER: 'spotbugs.bugDescriptions.fi_nullify_super',
  FI_USELESS: 'spotbugs.bugDescriptions.fi_useless',
  FI_MISSING_SUPER_CALL: 'spotbugs.bugDescriptions.fi_missing_super_call',
  FI_EXPLICIT_INVOCATION: 'spotbugs.bugDescriptions.fi_explicit_invocation',
  EQ_CHECK_FOR_OPERAND_NOT_COMPATIBLE_WITH_THIS: 'spotbugs.bugDescriptions.eq_check_for_operand_not_compatible_with_this',
  EQ_GETCLASS_AND_CLASS_CONSTANT: 'spotbugs.bugDescriptions.eq_getclass_and_class_constant',
  EQ_SELF_NO_OBJECT: 'spotbugs.bugDescriptions.eq_self_no_object',
  CO_SELF_NO_OBJECT: 'spotbugs.bugDescriptions.co_self_no_object',
  CO_COMPARETO_RESULTS_MIN_VALUE: 'spotbugs.bugDescriptions.co_compareto_results_min_value',
  CO_COMPARETO_INCORRECT_FLOATING: 'spotbugs.bugDescriptions.co_compareto_incorrect_floating',
  RV_NEGATING_RESULT_OF_COMPARETO: 'spotbugs.bugDescriptions.rv_negating_result_of_compareto',
  ES_COMPARING_STRINGS_WITH_EQ: 'spotbugs.bugDescriptions.es_comparing_strings_with_eq',
  ES_COMPARING_PARAMETER_STRING_WITH_EQ: 'spotbugs.bugDescriptions.es_comparing_parameter_string_with_eq',
  EQ_COMPARETO_USE_OBJECT_EQUALS: 'spotbugs.bugDescriptions.eq_compareto_use_object_equals',
  HE_HASHCODE_USE_OBJECT_EQUALS: 'spotbugs.bugDescriptions.he_hashcode_use_object_equals',
  HE_HASHCODE_NO_EQUALS: 'spotbugs.bugDescriptions.he_hashcode_no_equals',
  HE_EQUALS_USE_HASHCODE: 'spotbugs.bugDescriptions.he_equals_use_hashcode',
  HE_INHERITS_EQUALS_USE_HASHCODE: 'spotbugs.bugDescriptions.he_inherits_equals_use_hashcode',
  HE_EQUALS_NO_HASHCODE: 'spotbugs.bugDescriptions.he_equals_no_hashcode',
  EQ_ABSTRACT_SELF: 'spotbugs.bugDescriptions.eq_abstract_self',
  CO_ABSTRACT_SELF: 'spotbugs.bugDescriptions.co_abstract_self',
  IC_SUPERCLASS_USES_SUBCLASS_DURING_INITIALIZATION: 'spotbugs.bugDescriptions.ic_superclass_uses_subclass_during_initialization',
  SI_INSTANCE_BEFORE_FINALS_ASSIGNED: 'spotbugs.bugDescriptions.si_instance_before_finals_assigned',
  IT_NO_SUCH_ELEMENT: 'spotbugs.bugDescriptions.it_no_such_element',
  ME_MUTABLE_ENUM_FIELD: 'spotbugs.bugDescriptions.me_mutable_enum_field',
  ME_ENUM_FIELD_SETTER: 'spotbugs.bugDescriptions.me_enum_field_setter',
  NM_METHOD_NAMING_CONVENTION: 'spotbugs.bugDescriptions.nm_method_naming_convention',
  NM_FIELD_NAMING_CONVENTION: 'spotbugs.bugDescriptions.nm_field_naming_convention',
  NM_SAME_SIMPLE_NAME_AS_INTERFACE: 'spotbugs.bugDescriptions.nm_same_simple_name_as_interface',
  NM_SAME_SIMPLE_NAME_AS_SUPERCLASS: 'spotbugs.bugDescriptions.nm_same_simple_name_as_superclass',
  NM_CLASS_NAMING_CONVENTION: 'spotbugs.bugDescriptions.nm_class_naming_convention',
  NM_VERY_CONFUSING_INTENTIONAL: 'spotbugs.bugDescriptions.nm_very_confusing_intentional',
  NM_WRONG_PACKAGE_INTENTIONAL: 'spotbugs.bugDescriptions.nm_wrong_package_intentional',
  NM_CONFUSING: 'spotbugs.bugDescriptions.nm_confusing',
  NM_CLASS_NOT_EXCEPTION: 'spotbugs.bugDescriptions.nm_class_not_exception',
  RR_NOT_CHECKED: 'spotbugs.bugDescriptions.rr_not_checked',
  SR_NOT_CHECKED: 'spotbugs.bugDescriptions.sr_not_checked',
  SE_NO_SUITABLE_CONSTRUCTOR: 'spotbugs.bugDescriptions.se_no_suitable_constructor',
  SE_NO_SUITABLE_CONSTRUCTOR_FOR_EXTERNALIZATION: 'spotbugs.bugDescriptions.se_no_suitable_constructor_for_externalization',
  SE_COMPARATOR_SHOULD_BE_SERIALIZABLE: 'spotbugs.bugDescriptions.se_comparator_should_be_serializable',
  SE_NO_SERIALVERSIONID: 'spotbugs.bugDescriptions.se_no_serialversionid',
  SE_READ_RESOLVE_MUST_RETURN_OBJECT: 'spotbugs.bugDescriptions.se_read_resolve_must_return_object',
  SE_TRANSIENT_FIELD_NOT_RESTORED: 'spotbugs.bugDescriptions.se_transient_field_not_restored',
  SE_PREVENT_EXT_OBJ_OVERWRITE: 'spotbugs.bugDescriptions.se_prevent_ext_obj_overwrite',
  SE_NONFINAL_SERIALVERSIONID: 'spotbugs.bugDescriptions.se_nonfinal_serialversionid',
  SE_NONSTATIC_SERIALVERSIONID: 'spotbugs.bugDescriptions.se_nonstatic_serialversionid',
  SE_NONLONG_SERIALVERSIONID: 'spotbugs.bugDescriptions.se_nonlong_serialversionid',
  SE_BAD_FIELD: 'spotbugs.bugDescriptions.se_bad_field',
  SE_INNER_CLASS: 'spotbugs.bugDescriptions.se_inner_class',
  SE_BAD_FIELD_INNER_CLASS: 'spotbugs.bugDescriptions.se_bad_field_inner_class',
  SE_BAD_FIELD_STORE: 'spotbugs.bugDescriptions.se_bad_field_store',
  RV_RETURN_VALUE_IGNORED_BAD_PRACTICE: 'spotbugs.bugDescriptions.rv_return_value_ignored_bad_practice',
  NP_TOSTRING_COULD_RETURN_NULL: 'spotbugs.bugDescriptions.np_tostring_could_return_null',
  NP_CLONE_COULD_RETURN_NULL: 'spotbugs.bugDescriptions.np_clone_could_return_null',
  OS_OPEN_STREAM: 'spotbugs.bugDescriptions.os_open_stream',
  OS_OPEN_STREAM_EXCEPTION_PATH: 'spotbugs.bugDescriptions.os_open_stream_exception_path',
  RC_REF_COMPARISON_BAD_PRACTICE: 'spotbugs.bugDescriptions.rc_ref_comparison_bad_practice',
  RC_REF_COMPARISON_BAD_PRACTICE_BOOLEAN: 'spotbugs.bugDescriptions.rc_ref_comparison_bad_practice_boolean',
  VA_FORMAT_STRING_USES_NEWLINE: 'spotbugs.bugDescriptions.va_format_string_uses_newline',
  FS_BAD_DATE_FORMAT_FLAG_COMBO: 'spotbugs.bugDescriptions.fs_bad_date_format_flag_combo',
  BIT_SIGNED_CHECK: 'spotbugs.bugDescriptions.bit_signed_check',
  ODR_OPEN_DATABASE_RESOURCE: 'spotbugs.bugDescriptions.odr_open_database_resource',
  ODR_OPEN_DATABASE_RESOURCE_EXCEPTION_PATH: 'spotbugs.bugDescriptions.odr_open_database_resource_exception_path',
  ISC_INSTANTIATE_STATIC_CLASS: 'spotbugs.bugDescriptions.isc_instantiate_static_class',
  DMI_RANDOM_USED_ONLY_ONCE: 'spotbugs.bugDescriptions.dmi_random_used_only_once',
  BC_EQUALS_METHOD_SHOULD_WORK_FOR_ALL_OBJECTS: 'spotbugs.bugDescriptions.bc_equals_method_should_work_for_all_objects',
  J2EE_STORE_OF_NON_SERIALIZABLE_OBJECT_INTO_SESSION: 'spotbugs.bugDescriptions.j2_ee_store_of_non_serializable_object_into_session',
  GC_UNCHECKED_TYPE_IN_GENERIC_CALL: 'spotbugs.bugDescriptions.gc_unchecked_type_in_generic_call',
  PZ_DONT_REUSE_ENTRY_OBJECTS_IN_ITERATORS: 'spotbugs.bugDescriptions.pz_dont_reuse_entry_objects_in_iterators',
  DMI_ENTRY_SETS_MAY_REUSE_ENTRY_OBJECTS: 'spotbugs.bugDescriptions.dmi_entry_sets_may_reuse_entry_objects',
  DMI_USING_REMOVEALL_TO_CLEAR_COLLECTION: 'spotbugs.bugDescriptions.dmi_using_removeall_to_clear_collection',
  THROWS_METHOD_THROWS_RUNTIMEEXCEPTION: 'spotbugs.bugDescriptions.throws_method_throws_runtimeexception',
  THROWS_METHOD_THROWS_CLAUSE_BASIC_EXCEPTION: 'spotbugs.bugDescriptions.throws_method_throws_clause_basic_exception',
  THROWS_METHOD_THROWS_CLAUSE_THROWABLE: 'spotbugs.bugDescriptions.throws_method_throws_clause_throwable',
  PA_PUBLIC_PRIMITIVE_ATTRIBUTE: 'spotbugs.bugDescriptions.pa_public_primitive_attribute',
  PA_PUBLIC_ARRAY_ATTRIBUTE: 'spotbugs.bugDescriptions.pa_public_array_attribute',
  PA_PUBLIC_MUTABLE_OBJECT_ATTRIBUTE: 'spotbugs.bugDescriptions.pa_public_mutable_object_attribute',
  PI_DO_NOT_REUSE_PUBLIC_IDENTIFIERS_CLASS_NAMES: 'spotbugs.bugDescriptions.pi_do_not_reuse_public_identifiers_class_names',
  PI_DO_NOT_REUSE_PUBLIC_IDENTIFIERS_FIELD_NAMES: 'spotbugs.bugDescriptions.pi_do_not_reuse_public_identifiers_field_names',
  PI_DO_NOT_REUSE_PUBLIC_IDENTIFIERS_METHOD_NAMES: 'spotbugs.bugDescriptions.pi_do_not_reuse_public_identifiers_method_names',
  PI_DO_NOT_REUSE_PUBLIC_IDENTIFIERS_LOCAL_VARIABLE_NAMES: 'spotbugs.bugDescriptions.pi_do_not_reuse_public_identifiers_local_variable_names',
  ENV_USE_PROPERTY_INSTEAD_OF_ENV: 'spotbugs.bugDescriptions.env_use_property_instead_of_env',
  OVERRIDING_METHODS_MUST_INVOKE_SUPER: 'spotbugs.bugDescriptions.overriding_methods_must_invoke_super',
  NP_OPTIONAL_RETURN_NULL: 'spotbugs.bugDescriptions.np_optional_return_null',
  NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR: 'spotbugs.bugDescriptions.np_nonnull_field_not_initialized_in_constructor',
  VR_UNRESOLVABLE_REFERENCE: 'spotbugs.bugDescriptions.vr_unresolvable_reference',
  IL_INFINITE_LOOP: 'spotbugs.bugDescriptions.il_infinite_loop',
  IO_APPENDING_TO_OBJECT_OUTPUT_STREAM: 'spotbugs.bugDescriptions.io_appending_to_object_output_stream',
  IL_INFINITE_RECURSIVE_LOOP: 'spotbugs.bugDescriptions.il_infinite_recursive_loop',
  IL_CONTAINER_ADDED_TO_ITSELF: 'spotbugs.bugDescriptions.il_container_added_to_itself',
  RpC_REPEATED_CONDITIONAL_TEST: 'spotbugs.bugDescriptions.rp_c_repeated_conditional_test',
  FL_MATH_USING_FLOAT_PRECISION: 'spotbugs.bugDescriptions.fl_math_using_float_precision',
  CAA_COVARIANT_ARRAY_ELEMENT_STORE: 'spotbugs.bugDescriptions.caa_covariant_array_element_store',
  DMI_VACUOUS_CALL_TO_EASYMOCK_METHOD: 'spotbugs.bugDescriptions.dmi_vacuous_call_to_easymock_method',
  DMI_FUTILE_ATTEMPT_TO_CHANGE_MAXPOOL_SIZE_OF_SCHEDULED_THREAD_POOL_EXECUTOR:
    'spotbugs.bugDescriptions.dmi_futile_attempt_to_change_maxpool_size_of_scheduled_thread_pool_executor',
  DMI_BIGDECIMAL_CONSTRUCTED_FROM_DOUBLE: 'spotbugs.bugDescriptions.dmi_bigdecimal_constructed_from_double',
  DMI_SCHEDULED_THREAD_POOL_EXECUTOR_WITH_ZERO_CORE_THREADS: 'spotbugs.bugDescriptions.dmi_scheduled_thread_pool_executor_with_zero_core_threads',
  DMI_ANNOTATION_IS_NOT_VISIBLE_TO_REFLECTION: 'spotbugs.bugDescriptions.dmi_annotation_is_not_visible_to_reflection',
  NP_ARGUMENT_MIGHT_BE_NULL: 'spotbugs.bugDescriptions.np_argument_might_be_null',
  RV_ABSOLUTE_VALUE_OF_RANDOM_INT: 'spotbugs.bugDescriptions.rv_absolute_value_of_random_int',
  RV_ABSOLUTE_VALUE_OF_HASHCODE: 'spotbugs.bugDescriptions.rv_absolute_value_of_hashcode',
  RV_01_TO_INT: 'spotbugs.bugDescriptions.rv_01_to_int',
  DM_INVALID_MIN_MAX: 'spotbugs.bugDescriptions.dm_invalid_min_max',
  EQ_COMPARING_CLASS_NAMES: 'spotbugs.bugDescriptions.eq_comparing_class_names',
  EQ_ALWAYS_TRUE: 'spotbugs.bugDescriptions.eq_always_true',
  EQ_ALWAYS_FALSE: 'spotbugs.bugDescriptions.eq_always_false',
  EQ_OVERRIDING_EQUALS_NOT_SYMMETRIC: 'spotbugs.bugDescriptions.eq_overriding_equals_not_symmetric',
  EQ_DONT_DEFINE_EQUALS_FOR_ENUM: 'spotbugs.bugDescriptions.eq_dont_define_equals_for_enum',
  EQ_SELF_USE_OBJECT: 'spotbugs.bugDescriptions.eq_self_use_object',
  EQ_OTHER_USE_OBJECT: 'spotbugs.bugDescriptions.eq_other_use_object',
  EQ_OTHER_NO_OBJECT: 'spotbugs.bugDescriptions.eq_other_no_object',
  HE_SIGNATURE_DECLARES_HASHING_OF_UNHASHABLE_CLASS: 'spotbugs.bugDescriptions.he_signature_declares_hashing_of_unhashable_class',
  HE_USE_OF_UNHASHABLE_CLASS: 'spotbugs.bugDescriptions.he_use_of_unhashable_class',
  UR_UNINIT_READ: 'spotbugs.bugDescriptions.ur_uninit_read',
  UR_UNINIT_READ_CALLED_FROM_SUPER_CONSTRUCTOR: 'spotbugs.bugDescriptions.ur_uninit_read_called_from_super_constructor',
  NM_VERY_CONFUSING: 'spotbugs.bugDescriptions.nm_very_confusing',
  NM_WRONG_PACKAGE: 'spotbugs.bugDescriptions.nm_wrong_package',
  NM_METHOD_CONSTRUCTOR_CONFUSION: 'spotbugs.bugDescriptions.nm_method_constructor_confusion',
  NM_LCASE_HASHCODE: 'spotbugs.bugDescriptions.nm_lcase_hashcode',
  NM_LCASE_TOSTRING: 'spotbugs.bugDescriptions.nm_lcase_tostring',
  NM_BAD_EQUAL: 'spotbugs.bugDescriptions.nm_bad_equal',
  SE_READ_RESOLVE_IS_STATIC: 'spotbugs.bugDescriptions.se_read_resolve_is_static',
  SE_METHOD_MUST_BE_PRIVATE: 'spotbugs.bugDescriptions.se_method_must_be_private',
  SF_DEAD_STORE_DUE_TO_SWITCH_FALLTHROUGH: 'spotbugs.bugDescriptions.sf_dead_store_due_to_switch_fallthrough',
  SF_DEAD_STORE_DUE_TO_SWITCH_FALLTHROUGH_TO_THROW: 'spotbugs.bugDescriptions.sf_dead_store_due_to_switch_fallthrough_to_throw',
  NP_UNWRITTEN_FIELD: 'spotbugs.bugDescriptions.np_unwritten_field',
  UWF_NULL_FIELD: 'spotbugs.bugDescriptions.uwf_null_field',
  UWF_UNWRITTEN_FIELD: 'spotbugs.bugDescriptions.uwf_unwritten_field',
  SIC_THREADLOCAL_DEADLY_EMBRACE: 'spotbugs.bugDescriptions.sic_threadlocal_deadly_embrace',
  RANGE_ARRAY_INDEX: 'spotbugs.bugDescriptions.range_array_index',
  RANGE_ARRAY_OFFSET: 'spotbugs.bugDescriptions.range_array_offset',
  RANGE_ARRAY_LENGTH: 'spotbugs.bugDescriptions.range_array_length',
  RANGE_STRING_INDEX: 'spotbugs.bugDescriptions.range_string_index',
  RV_RETURN_VALUE_IGNORED: 'spotbugs.bugDescriptions.rv_return_value_ignored',
  RV_EXCEPTION_NOT_THROWN: 'spotbugs.bugDescriptions.rv_exception_not_thrown',
  RV_CHECK_COMPARETO_FOR_SPECIFIC_RETURN_VALUE: 'spotbugs.bugDescriptions.rv_check_compareto_for_specific_return_value',
  NP_ALWAYS_NULL: 'spotbugs.bugDescriptions.np_always_null',
  NP_CLOSING_NULL: 'spotbugs.bugDescriptions.np_closing_null',
  NP_STORE_INTO_NONNULL_FIELD: 'spotbugs.bugDescriptions.np_store_into_nonnull_field',
  NP_ALWAYS_NULL_EXCEPTION: 'spotbugs.bugDescriptions.np_always_null_exception',
  NP_NULL_ON_SOME_PATH: 'spotbugs.bugDescriptions.np_null_on_some_path',
  NP_NULL_ON_SOME_PATH_EXCEPTION: 'spotbugs.bugDescriptions.np_null_on_some_path_exception',
  NP_NULL_PARAM_DEREF: 'spotbugs.bugDescriptions.np_null_param_deref',
  NP_NULL_PARAM_DEREF_NONVIRTUAL: 'spotbugs.bugDescriptions.np_null_param_deref_nonvirtual',
  NP_NULL_PARAM_DEREF_ALL_TARGETS_DANGEROUS: 'spotbugs.bugDescriptions.np_null_param_deref_all_targets_dangerous',
  NP_NONNULL_PARAM_VIOLATION: 'spotbugs.bugDescriptions.np_nonnull_param_violation',
  NP_NONNULL_RETURN_VIOLATION: 'spotbugs.bugDescriptions.np_nonnull_return_violation',
  NP_GUARANTEED_DEREF: 'spotbugs.bugDescriptions.np_guaranteed_deref',
  NP_GUARANTEED_DEREF_ON_EXCEPTION_PATH: 'spotbugs.bugDescriptions.np_guaranteed_deref_on_exception_path',
  DMI_ARGUMENTS_WRONG_ORDER: 'spotbugs.bugDescriptions.dmi_arguments_wrong_order',
  RCN_REDUNDANT_NULLCHECK_WOULD_HAVE_BEEN_A_NPE: 'spotbugs.bugDescriptions.rcn_redundant_nullcheck_would_have_been_a_npe',
  RC_REF_COMPARISON: 'spotbugs.bugDescriptions.rc_ref_comparison',
  VA_PRIMITIVE_ARRAY_PASSED_TO_OBJECT_VARARG: 'spotbugs.bugDescriptions.va_primitive_array_passed_to_object_vararg',
  EC_UNRELATED_TYPES_USING_POINTER_EQUALITY: 'spotbugs.bugDescriptions.ec_unrelated_types_using_pointer_equality',
  EC_UNRELATED_TYPES: 'spotbugs.bugDescriptions.ec_unrelated_types',
  EC_ARRAY_AND_NONARRAY: 'spotbugs.bugDescriptions.ec_array_and_nonarray',
  EC_NULL_ARG: 'spotbugs.bugDescriptions.ec_null_arg',
  EC_UNRELATED_INTERFACES: 'spotbugs.bugDescriptions.ec_unrelated_interfaces',
  EC_UNRELATED_CLASS_AND_INTERFACE: 'spotbugs.bugDescriptions.ec_unrelated_class_and_interface',
  SA_LOCAL_SELF_ASSIGNMENT_INSTEAD_OF_FIELD: 'spotbugs.bugDescriptions.sa_local_self_assignment_instead_of_field',
  INT_BAD_COMPARISON_WITH_INT_VALUE: 'spotbugs.bugDescriptions.int_bad_comparison_with_int_value',
  INT_BAD_COMPARISON_WITH_SIGNED_BYTE: 'spotbugs.bugDescriptions.int_bad_comparison_with_signed_byte',
  INT_BAD_COMPARISON_WITH_NONNEGATIVE_VALUE: 'spotbugs.bugDescriptions.int_bad_comparison_with_nonnegative_value',
  BIT_ADD_OF_SIGNED_BYTE: 'spotbugs.bugDescriptions.bit_add_of_signed_byte',
  BIT_IOR_OF_SIGNED_BYTE: 'spotbugs.bugDescriptions.bit_ior_of_signed_byte',
  BIT_SIGNED_CHECK_HIGH_BIT: 'spotbugs.bugDescriptions.bit_signed_check_high_bit',
  BIT_AND: 'spotbugs.bugDescriptions.bit_and',
  BIT_AND_ZZ: 'spotbugs.bugDescriptions.bit_and_zz',
  BIT_IOR: 'spotbugs.bugDescriptions.bit_ior',
  SA_FIELD_SELF_ASSIGNMENT: 'spotbugs.bugDescriptions.sa_field_self_assignment',
  SA_FIELD_SELF_COMPUTATION: 'spotbugs.bugDescriptions.sa_field_self_computation',
  SA_LOCAL_SELF_COMPUTATION: 'spotbugs.bugDescriptions.sa_local_self_computation',
  SA_FIELD_SELF_COMPARISON: 'spotbugs.bugDescriptions.sa_field_self_comparison',
  SA_LOCAL_SELF_COMPARISON: 'spotbugs.bugDescriptions.sa_local_self_comparison',
  UMAC_UNCALLABLE_METHOD_OF_ANONYMOUS_CLASS: 'spotbugs.bugDescriptions.umac_uncallable_method_of_anonymous_class',
  IJU_ASSERT_METHOD_INVOKED_FROM_RUN_METHOD: 'spotbugs.bugDescriptions.iju_assert_method_invoked_from_run_method',
  IJU_BAD_SUITE_METHOD: 'spotbugs.bugDescriptions.iju_bad_suite_method',
  IJU_SETUP_NO_SUPER: 'spotbugs.bugDescriptions.iju_setup_no_super',
  IJU_TEARDOWN_NO_SUPER: 'spotbugs.bugDescriptions.iju_teardown_no_super',
  IJU_SUITE_NOT_STATIC: 'spotbugs.bugDescriptions.iju_suite_not_static',
  IJU_NO_TESTS: 'spotbugs.bugDescriptions.iju_no_tests',
  BOA_BADLY_OVERRIDDEN_ADAPTER: 'spotbugs.bugDescriptions.boa_badly_overridden_adapter',
  SQL_BAD_RESULTSET_ACCESS: 'spotbugs.bugDescriptions.sql_bad_resultset_access',
  SQL_BAD_PREPARED_STATEMENT_ACCESS: 'spotbugs.bugDescriptions.sql_bad_prepared_statement_access',
  SIO_SUPERFLUOUS_INSTANCEOF: 'spotbugs.bugDescriptions.sio_superfluous_instanceof',
  BAC_BAD_APPLET_CONSTRUCTOR: 'spotbugs.bugDescriptions.bac_bad_applet_constructor',
  EC_INCOMPATIBLE_ARRAY_COMPARE: 'spotbugs.bugDescriptions.ec_incompatible_array_compare',
  EC_BAD_ARRAY_COMPARE: 'spotbugs.bugDescriptions.ec_bad_array_compare',
  STI_INTERRUPTED_ON_CURRENTTHREAD: 'spotbugs.bugDescriptions.sti_interrupted_on_currentthread',
  STI_INTERRUPTED_ON_UNKNOWNTHREAD: 'spotbugs.bugDescriptions.sti_interrupted_on_unknownthread',
  DLS_DEAD_LOCAL_INCREMENT_IN_RETURN: 'spotbugs.bugDescriptions.dls_dead_local_increment_in_return',
  DLS_DEAD_STORE_OF_CLASS_LITERAL: 'spotbugs.bugDescriptions.dls_dead_store_of_class_literal',
  IP_PARAMETER_IS_DEAD_BUT_OVERWRITTEN: 'spotbugs.bugDescriptions.ip_parameter_is_dead_but_overwritten',
  MF_METHOD_MASKS_FIELD: 'spotbugs.bugDescriptions.mf_method_masks_field',
  MF_CLASS_MASKS_FIELD: 'spotbugs.bugDescriptions.mf_class_masks_field',
  FE_TEST_IF_EQUAL_TO_NOT_A_NUMBER: 'spotbugs.bugDescriptions.fe_test_if_equal_to_not_a_number',
  ICAST_INT_2_LONG_AS_INSTANT: 'spotbugs.bugDescriptions.icast_int_2_long_as_instant',
  ICAST_INT_CAST_TO_DOUBLE_PASSED_TO_CEIL: 'spotbugs.bugDescriptions.icast_int_cast_to_double_passed_to_ceil',
  ICAST_INT_CAST_TO_FLOAT_PASSED_TO_ROUND: 'spotbugs.bugDescriptions.icast_int_cast_to_float_passed_to_round',
  NP_NULL_INSTANCEOF: 'spotbugs.bugDescriptions.np_null_instanceof',
  DMI_LONG_BITS_TO_DOUBLE_INVOKED_ON_INT: 'spotbugs.bugDescriptions.dmi_long_bits_to_double_invoked_on_int',
  BC_IMPOSSIBLE_CAST: 'spotbugs.bugDescriptions.bc_impossible_cast',
  BC_IMPOSSIBLE_DOWNCAST: 'spotbugs.bugDescriptions.bc_impossible_downcast',
  BC_IMPOSSIBLE_DOWNCAST_OF_TOARRAY: 'spotbugs.bugDescriptions.bc_impossible_downcast_of_toarray',
  BC_IMPOSSIBLE_INSTANCEOF: 'spotbugs.bugDescriptions.bc_impossible_instanceof',
  RE_POSSIBLE_UNINTENDED_PATTERN: 'spotbugs.bugDescriptions.re_possible_unintended_pattern',
  RE_BAD_SYNTAX_FOR_REGULAR_EXPRESSION: 'spotbugs.bugDescriptions.re_bad_syntax_for_regular_expression',
  RE_CANT_USE_FILE_SEPARATOR_AS_REGULAR_EXPRESSION: 'spotbugs.bugDescriptions.re_cant_use_file_separator_as_regular_expression',
  DLS_OVERWRITTEN_INCREMENT: 'spotbugs.bugDescriptions.dls_overwritten_increment',
  ICAST_BAD_SHIFT_AMOUNT: 'spotbugs.bugDescriptions.icast_bad_shift_amount',
  BSHIFT_WRONG_ADD_PRIORITY: 'spotbugs.bugDescriptions.bshift_wrong_add_priority',
  IM_MULTIPLYING_RESULT_OF_IREM: 'spotbugs.bugDescriptions.im_multiplying_result_of_irem',
  DMI_INVOKING_HASHCODE_ON_ARRAY: 'spotbugs.bugDescriptions.dmi_invoking_hashcode_on_array',
  DMI_INVOKING_TOSTRING_ON_ARRAY: 'spotbugs.bugDescriptions.dmi_invoking_tostring_on_array',
  DMI_INVOKING_TOSTRING_ON_ANONYMOUS_ARRAY: 'spotbugs.bugDescriptions.dmi_invoking_tostring_on_anonymous_array',
  DMI_BAD_MONTH: 'spotbugs.bugDescriptions.dmi_bad_month',
  DMI_CALLING_NEXT_FROM_HASNEXT: 'spotbugs.bugDescriptions.dmi_calling_next_from_hasnext',
  QBA_QUESTIONABLE_BOOLEAN_ASSIGNMENT: 'spotbugs.bugDescriptions.qba_questionable_boolean_assignment',
  GC_UNRELATED_TYPES: 'spotbugs.bugDescriptions.gc_unrelated_types',
  DMI_VACUOUS_SELF_COLLECTION_CALL: 'spotbugs.bugDescriptions.dmi_vacuous_self_collection_call',
  DMI_DOH: 'spotbugs.bugDescriptions.dmi_doh',
  DMI_COLLECTIONS_SHOULD_NOT_CONTAIN_THEMSELVES: 'spotbugs.bugDescriptions.dmi_collections_should_not_contain_themselves',
  TQ_UNKNOWN_VALUE_USED_WHERE_ALWAYS_STRICTLY_REQUIRED: 'spotbugs.bugDescriptions.tq_unknown_value_used_where_always_strictly_required',
  TQ_COMPARING_VALUES_WITH_INCOMPATIBLE_TYPE_QUALIFIERS: 'spotbugs.bugDescriptions.tq_comparing_values_with_incompatible_type_qualifiers',
  TQ_ALWAYS_VALUE_USED_WHERE_NEVER_REQUIRED: 'spotbugs.bugDescriptions.tq_always_value_used_where_never_required',
  TQ_NEVER_VALUE_USED_WHERE_ALWAYS_REQUIRED: 'spotbugs.bugDescriptions.tq_never_value_used_where_always_required',
  TQ_MAYBE_SOURCE_VALUE_REACHES_ALWAYS_SINK: 'spotbugs.bugDescriptions.tq_maybe_source_value_reaches_always_sink',
  TQ_MAYBE_SOURCE_VALUE_REACHES_NEVER_SINK: 'spotbugs.bugDescriptions.tq_maybe_source_value_reaches_never_sink',
  FB_UNEXPECTED_WARNING: 'spotbugs.bugDescriptions.fb_unexpected_warning',
  FB_MISSING_EXPECTED_WARNING: 'spotbugs.bugDescriptions.fb_missing_expected_warning',
  EOS_BAD_END_OF_STREAM_CHECK: 'spotbugs.bugDescriptions.eos_bad_end_of_stream_check',
  FL_FLOATS_AS_LOOP_COUNTERS: 'spotbugs.bugDescriptions.fl_floats_as_loop_counters',
  SING_SINGLETON_IMPLEMENTS_CLONEABLE: 'spotbugs.bugDescriptions.sing_singleton_implements_cloneable',
  SING_SINGLETON_INDIRECTLY_IMPLEMENTS_CLONEABLE: 'spotbugs.bugDescriptions.sing_singleton_indirectly_implements_cloneable',
  SING_SINGLETON_IMPLEMENTS_CLONE_METHOD: 'spotbugs.bugDescriptions.sing_singleton_implements_clone_method',
  SING_SINGLETON_HAS_NONPRIVATE_CONSTRUCTOR: 'spotbugs.bugDescriptions.sing_singleton_has_nonprivate_constructor',
  SING_SINGLETON_IMPLEMENTS_SERIALIZABLE: 'spotbugs.bugDescriptions.sing_singleton_implements_serializable',
  SING_SINGLETON_GETTER_NOT_SYNCHRONIZED: 'spotbugs.bugDescriptions.sing_singleton_getter_not_synchronized',
  HSM_HIDING_METHOD: 'spotbugs.bugDescriptions.hsm_hiding_method',
  SKIPPED_CLASS_TOO_BIG: 'spotbugs.bugDescriptions.skipped_class_too_big',
  UNKNOWN: 'spotbugs.bugDescriptions.unknown',
  TESTING: 'spotbugs.bugDescriptions.testing',
  TESTING1: 'spotbugs.bugDescriptions.testing1',
  TESTING2: 'spotbugs.bugDescriptions.testing2',
  TESTING3: 'spotbugs.bugDescriptions.testing3',
  OBL_UNSATISFIED_OBLIGATION: 'spotbugs.bugDescriptions.obl_unsatisfied_obligation',
  OBL_UNSATISFIED_OBLIGATION_EXCEPTION_EDGE: 'spotbugs.bugDescriptions.obl_unsatisfied_obligation_exception_edge',
  LG_LOST_LOGGER_DUE_TO_WEAK_REFERENCE: 'spotbugs.bugDescriptions.lg_lost_logger_due_to_weak_reference',
  DM_CONVERT_CASE: 'spotbugs.bugDescriptions.dm_convert_case',
  DM_DEFAULT_ENCODING: 'spotbugs.bugDescriptions.dm_default_encoding',
  DP_DO_INSIDE_DO_PRIVILEGED: 'spotbugs.bugDescriptions.dp_do_inside_do_privileged',
  DP_CREATE_CLASSLOADER_INSIDE_DO_PRIVILEGED: 'spotbugs.bugDescriptions.dp_create_classloader_inside_do_privileged',
  FI_PUBLIC_SHOULD_BE_PROTECTED: 'spotbugs.bugDescriptions.fi_public_should_be_protected',
  MS_EXPOSE_REP: 'spotbugs.bugDescriptions.ms_expose_rep',
  MS_EXPOSE_BUF: 'spotbugs.bugDescriptions.ms_expose_buf',
  EI_EXPOSE_REP: 'spotbugs.bugDescriptions.ei_expose_rep',
  EI_EXPOSE_BUF: 'spotbugs.bugDescriptions.ei_expose_buf',
  EI_EXPOSE_REP2: 'spotbugs.bugDescriptions.ei_expose_rep2',
  EI_EXPOSE_STATIC_REP2: 'spotbugs.bugDescriptions.ei_expose_static_rep2',
  EI_EXPOSE_BUF2: 'spotbugs.bugDescriptions.ei_expose_buf2',
  EI_EXPOSE_STATIC_BUF2: 'spotbugs.bugDescriptions.ei_expose_static_buf2',
  MS_OOI_PKGPROTECT: 'spotbugs.bugDescriptions.ms_ooi_pkgprotect',
  MS_FINAL_PKGPROTECT: 'spotbugs.bugDescriptions.ms_final_pkgprotect',
  MS_SHOULD_BE_FINAL: 'spotbugs.bugDescriptions.ms_should_be_final',
  MS_SHOULD_BE_REFACTORED_TO_BE_FINAL: 'spotbugs.bugDescriptions.ms_should_be_refactored_to_be_final',
  MS_PKGPROTECT: 'spotbugs.bugDescriptions.ms_pkgprotect',
  MS_MUTABLE_HASHTABLE: 'spotbugs.bugDescriptions.ms_mutable_hashtable',
  MS_MUTABLE_ARRAY: 'spotbugs.bugDescriptions.ms_mutable_array',
  MS_MUTABLE_COLLECTION: 'spotbugs.bugDescriptions.ms_mutable_collection',
  MS_MUTABLE_COLLECTION_PKGPROTECT: 'spotbugs.bugDescriptions.ms_mutable_collection_pkgprotect',
  MS_CANNOT_BE_FINAL: 'spotbugs.bugDescriptions.ms_cannot_be_final',
  REFLC_REFLECTION_MAY_INCREASE_ACCESSIBILITY_OF_CLASS: 'spotbugs.bugDescriptions.reflc_reflection_may_increase_accessibility_of_class',
  REFLF_REFLECTION_MAY_INCREASE_ACCESSIBILITY_OF_FIELD: 'spotbugs.bugDescriptions.reflf_reflection_may_increase_accessibility_of_field',
  MC_OVERRIDABLE_METHOD_CALL_IN_CONSTRUCTOR: 'spotbugs.bugDescriptions.mc_overridable_method_call_in_constructor',
  MC_OVERRIDABLE_METHOD_CALL_IN_CLONE: 'spotbugs.bugDescriptions.mc_overridable_method_call_in_clone',
  MC_OVERRIDABLE_METHOD_CALL_IN_READ_OBJECT: 'spotbugs.bugDescriptions.mc_overridable_method_call_in_read_object',
  PERM_SUPER_NOT_CALLED_IN_GETPERMISSIONS: 'spotbugs.bugDescriptions.perm_super_not_called_in_getpermissions',
  USC_POTENTIAL_SECURITY_CHECK_BASED_ON_UNTRUSTED_SOURCE: 'spotbugs.bugDescriptions.usc_potential_security_check_based_on_untrusted_source',
  VSC_VULNERABLE_SECURITY_CHECK_METHODS: 'spotbugs.bugDescriptions.vsc_vulnerable_security_check_methods',
  AT_OPERATION_SEQUENCE_ON_CONCURRENT_ABSTRACTION: 'spotbugs.bugDescriptions.at_operation_sequence_on_concurrent_abstraction',
  AT_UNSAFE_RESOURCE_ACCESS_IN_THREAD: 'spotbugs.bugDescriptions.at_unsafe_resource_access_in_thread',
  STCAL_STATIC_CALENDAR_INSTANCE: 'spotbugs.bugDescriptions.stcal_static_calendar_instance',
  STCAL_STATIC_SIMPLE_DATE_FORMAT_INSTANCE: 'spotbugs.bugDescriptions.stcal_static_simple_date_format_instance',
  STCAL_INVOKE_ON_STATIC_CALENDAR_INSTANCE: 'spotbugs.bugDescriptions.stcal_invoke_on_static_calendar_instance',
  STCAL_INVOKE_ON_STATIC_DATE_FORMAT_INSTANCE: 'spotbugs.bugDescriptions.stcal_invoke_on_static_date_format_instance',
  NP_SYNC_AND_NULL_CHECK_FIELD: 'spotbugs.bugDescriptions.np_sync_and_null_check_field',
  VO_VOLATILE_REFERENCE_TO_ARRAY: 'spotbugs.bugDescriptions.vo_volatile_reference_to_array',
  VO_VOLATILE_INCREMENT: 'spotbugs.bugDescriptions.vo_volatile_increment',
  DM_MONITOR_WAIT_ON_CONDITION: 'spotbugs.bugDescriptions.dm_monitor_wait_on_condition',
  DM_USELESS_THREAD: 'spotbugs.bugDescriptions.dm_useless_thread',
  DC_DOUBLECHECK: 'spotbugs.bugDescriptions.dc_doublecheck',
  DC_PARTIALLY_CONSTRUCTED: 'spotbugs.bugDescriptions.dc_partially_constructed',
  DL_SYNCHRONIZATION_ON_SHARED_CONSTANT: 'spotbugs.bugDescriptions.dl_synchronization_on_shared_constant',
  DL_SYNCHRONIZATION_ON_BOOLEAN: 'spotbugs.bugDescriptions.dl_synchronization_on_boolean',
  DL_SYNCHRONIZATION_ON_BOXED_PRIMITIVE: 'spotbugs.bugDescriptions.dl_synchronization_on_boxed_primitive',
  DL_SYNCHRONIZATION_ON_UNSHARED_BOXED_PRIMITIVE: 'spotbugs.bugDescriptions.dl_synchronization_on_unshared_boxed_primitive',
  DL_SYNCHRONIZATION_ON_INTERNED_STRING: 'spotbugs.bugDescriptions.dl_synchronization_on_interned_string',
  WL_USING_GETCLASS_RATHER_THAN_CLASS_LITERAL: 'spotbugs.bugDescriptions.wl_using_getclass_rather_than_class_literal',
  ESync_EMPTY_SYNC: 'spotbugs.bugDescriptions.e_sync_empty_sync',
  MSF_MUTABLE_SERVLET_FIELD: 'spotbugs.bugDescriptions.msf_mutable_servlet_field',
  IS2_INCONSISTENT_SYNC: 'spotbugs.bugDescriptions.is2_inconsistent_sync',
  NN_NAKED_NOTIFY: 'spotbugs.bugDescriptions.nn_naked_notify',
  RU_INVOKE_RUN: 'spotbugs.bugDescriptions.ru_invoke_run',
  SP_SPIN_ON_FIELD: 'spotbugs.bugDescriptions.sp_spin_on_field',
  TLW_TWO_LOCK_WAIT: 'spotbugs.bugDescriptions.tlw_two_lock_wait',
  UW_UNCOND_WAIT: 'spotbugs.bugDescriptions.uw_uncond_wait',
  UG_SYNC_SET_UNSYNC_GET: 'spotbugs.bugDescriptions.ug_sync_set_unsync_get',
  IS_FIELD_NOT_GUARDED: 'spotbugs.bugDescriptions.is_field_not_guarded',
  ML_SYNC_ON_FIELD_TO_GUARD_CHANGING_THAT_FIELD: 'spotbugs.bugDescriptions.ml_sync_on_field_to_guard_changing_that_field',
  ML_SYNC_ON_UPDATED_FIELD: 'spotbugs.bugDescriptions.ml_sync_on_updated_field',
  WS_WRITEOBJECT_SYNC: 'spotbugs.bugDescriptions.ws_writeobject_sync',
  RS_READOBJECT_SYNC: 'spotbugs.bugDescriptions.rs_readobject_sync',
  SC_START_IN_CTOR: 'spotbugs.bugDescriptions.sc_start_in_ctor',
  WA_NOT_IN_LOOP: 'spotbugs.bugDescriptions.wa_not_in_loop',
  WA_AWAIT_NOT_IN_LOOP: 'spotbugs.bugDescriptions.wa_await_not_in_loop',
  NO_NOTIFY_NOT_NOTIFYALL: 'spotbugs.bugDescriptions.no_notify_not_notifyall',
  UL_UNRELEASED_LOCK: 'spotbugs.bugDescriptions.ul_unreleased_lock',
  UL_UNRELEASED_LOCK_EXCEPTION_PATH: 'spotbugs.bugDescriptions.ul_unreleased_lock_exception_path',
  MWN_MISMATCHED_WAIT: 'spotbugs.bugDescriptions.mwn_mismatched_wait',
  MWN_MISMATCHED_NOTIFY: 'spotbugs.bugDescriptions.mwn_mismatched_notify',
  LI_LAZY_INIT_STATIC: 'spotbugs.bugDescriptions.li_lazy_init_static',
  LI_LAZY_INIT_UPDATE_STATIC: 'spotbugs.bugDescriptions.li_lazy_init_update_static',
  JLM_JSR166_UTILCONCURRENT_MONITORENTER: 'spotbugs.bugDescriptions.jlm_jsr166_utilconcurrent_monitorenter',
  JML_JSR166_CALLING_WAIT_RATHER_THAN_AWAIT: 'spotbugs.bugDescriptions.jml_jsr166_calling_wait_rather_than_await',
  JLM_JSR166_LOCK_MONITORENTER: 'spotbugs.bugDescriptions.jlm_jsr166_lock_monitorenter',
  SWL_SLEEP_WITH_LOCK_HELD: 'spotbugs.bugDescriptions.swl_sleep_with_lock_held',
  RV_RETURN_VALUE_OF_PUTIFABSENT_IGNORED: 'spotbugs.bugDescriptions.rv_return_value_of_putifabsent_ignored',
  SSD_DO_NOT_USE_INSTANCE_LOCK_ON_SHARED_STATIC_DATA: 'spotbugs.bugDescriptions.ssd_do_not_use_instance_lock_on_shared_static_data',
  AT_NONATOMIC_64BIT_PRIMITIVE: 'spotbugs.bugDescriptions.at_nonatomic_64_bit_primitive',
  AT_STALE_THREAD_WRITE_OF_PRIMITIVE: 'spotbugs.bugDescriptions.at_stale_thread_write_of_primitive',
  AT_NONATOMIC_OPERATIONS_ON_SHARED_VARIABLE: 'spotbugs.bugDescriptions.at_nonatomic_operations_on_shared_variable',
  NOISE_NULL_DEREFERENCE: 'spotbugs.bugDescriptions.noise_null_dereference',
  NOISE_METHOD_CALL: 'spotbugs.bugDescriptions.noise_method_call',
  NOISE_FIELD_REFERENCE: 'spotbugs.bugDescriptions.noise_field_reference',
  NOISE_OPERATION: 'spotbugs.bugDescriptions.noise_operation',
  HSC_HUGE_SHARED_STRING_CONSTANT: 'spotbugs.bugDescriptions.hsc_huge_shared_string_constant',
  DMI_BLOCKING_METHODS_ON_URL: 'spotbugs.bugDescriptions.dmi_blocking_methods_on_url',
  DMI_COLLECTION_OF_URLS: 'spotbugs.bugDescriptions.dmi_collection_of_urls',
  DM_STRING_CTOR: 'spotbugs.bugDescriptions.dm_string_ctor',
  DM_STRING_VOID_CTOR: 'spotbugs.bugDescriptions.dm_string_void_ctor',
  DM_STRING_TOSTRING: 'spotbugs.bugDescriptions.dm_string_tostring',
  DM_GC: 'spotbugs.bugDescriptions.dm_gc',
  DM_BOOLEAN_CTOR: 'spotbugs.bugDescriptions.dm_boolean_ctor',
  DM_NUMBER_CTOR: 'spotbugs.bugDescriptions.dm_number_ctor',
  DM_FP_NUMBER_CTOR: 'spotbugs.bugDescriptions.dm_fp_number_ctor',
  DM_BOXED_PRIMITIVE_TOSTRING: 'spotbugs.bugDescriptions.dm_boxed_primitive_tostring',
  DM_BOXED_PRIMITIVE_FOR_PARSING: 'spotbugs.bugDescriptions.dm_boxed_primitive_for_parsing',
  DM_BOXED_PRIMITIVE_FOR_COMPARE: 'spotbugs.bugDescriptions.dm_boxed_primitive_for_compare',
  BX_UNBOXED_AND_COERCED_FOR_TERNARY_OPERATOR: 'spotbugs.bugDescriptions.bx_unboxed_and_coerced_for_ternary_operator',
  BX_UNBOXING_IMMEDIATELY_REBOXED: 'spotbugs.bugDescriptions.bx_unboxing_immediately_reboxed',
  BX_BOXING_IMMEDIATELY_UNBOXED: 'spotbugs.bugDescriptions.bx_boxing_immediately_unboxed',
  BX_BOXING_IMMEDIATELY_UNBOXED_TO_PERFORM_COERCION: 'spotbugs.bugDescriptions.bx_boxing_immediately_unboxed_to_perform_coercion',
  DM_NEW_FOR_GETCLASS: 'spotbugs.bugDescriptions.dm_new_for_getclass',
  DM_NEXTINT_VIA_NEXTDOUBLE: 'spotbugs.bugDescriptions.dm_nextint_via_nextdouble',
  SS_SHOULD_BE_STATIC: 'spotbugs.bugDescriptions.ss_should_be_static',
  UUF_UNUSED_FIELD: 'spotbugs.bugDescriptions.uuf_unused_field',
  URF_UNREAD_FIELD: 'spotbugs.bugDescriptions.urf_unread_field',
  SIC_INNER_SHOULD_BE_STATIC: 'spotbugs.bugDescriptions.sic_inner_should_be_static',
  SIC_INNER_SHOULD_BE_STATIC_NEEDS_THIS: 'spotbugs.bugDescriptions.sic_inner_should_be_static_needs_this',
  SIC_INNER_SHOULD_BE_STATIC_ANON: 'spotbugs.bugDescriptions.sic_inner_should_be_static_anon',
  UPM_UNCALLED_PRIVATE_METHOD: 'spotbugs.bugDescriptions.upm_uncalled_private_method',
  SBSC_USE_STRINGBUFFER_CONCATENATION: 'spotbugs.bugDescriptions.sbsc_use_stringbuffer_concatenation',
  IIL_ELEMENTS_GET_LENGTH_IN_LOOP: 'spotbugs.bugDescriptions.iil_elements_get_length_in_loop',
  IIL_PREPARE_STATEMENT_IN_LOOP: 'spotbugs.bugDescriptions.iil_prepare_statement_in_loop',
  IIL_PATTERN_COMPILE_IN_LOOP: 'spotbugs.bugDescriptions.iil_pattern_compile_in_loop',
  IIL_PATTERN_COMPILE_IN_LOOP_INDIRECT: 'spotbugs.bugDescriptions.iil_pattern_compile_in_loop_indirect',
  IIO_INEFFICIENT_INDEX_OF: 'spotbugs.bugDescriptions.iio_inefficient_index_of',
  IIO_INEFFICIENT_LAST_INDEX_OF: 'spotbugs.bugDescriptions.iio_inefficient_last_index_of',
  ITA_INEFFICIENT_TO_ARRAY: 'spotbugs.bugDescriptions.ita_inefficient_to_array',
  WMI_WRONG_MAP_ITERATOR: 'spotbugs.bugDescriptions.wmi_wrong_map_iterator',
  UM_UNNECESSARY_MATH: 'spotbugs.bugDescriptions.um_unnecessary_math',
  IMA_INEFFICIENT_MEMBER_ACCESS: 'spotbugs.bugDescriptions.ima_inefficient_member_access',
  XSS_REQUEST_PARAMETER_TO_SEND_ERROR: 'spotbugs.bugDescriptions.xss_request_parameter_to_send_error',
  XSS_REQUEST_PARAMETER_TO_SERVLET_WRITER: 'spotbugs.bugDescriptions.xss_request_parameter_to_servlet_writer',
  XSS_REQUEST_PARAMETER_TO_JSP_WRITER: 'spotbugs.bugDescriptions.xss_request_parameter_to_jsp_writer',
  HRS_REQUEST_PARAMETER_TO_HTTP_HEADER: 'spotbugs.bugDescriptions.hrs_request_parameter_to_http_header',
  HRS_REQUEST_PARAMETER_TO_COOKIE: 'spotbugs.bugDescriptions.hrs_request_parameter_to_cookie',
  PT_ABSOLUTE_PATH_TRAVERSAL: 'spotbugs.bugDescriptions.pt_absolute_path_traversal',
  PT_RELATIVE_PATH_TRAVERSAL: 'spotbugs.bugDescriptions.pt_relative_path_traversal',
  DMI_CONSTANT_DB_PASSWORD: 'spotbugs.bugDescriptions.dmi_constant_db_password',
  DMI_EMPTY_DB_PASSWORD: 'spotbugs.bugDescriptions.dmi_empty_db_password',
  SQL_NONCONSTANT_STRING_PASSED_TO_EXECUTE: 'spotbugs.bugDescriptions.sql_nonconstant_string_passed_to_execute',
  SQL_PREPARED_STATEMENT_GENERATED_FROM_NONCONSTANT_STRING: 'spotbugs.bugDescriptions.sql_prepared_statement_generated_from_nonconstant_string',
  ASE_ASSERTION_WITH_SIDE_EFFECT: 'spotbugs.bugDescriptions.ase_assertion_with_side_effect',
  ASE_ASSERTION_WITH_SIDE_EFFECT_METHOD: 'spotbugs.bugDescriptions.ase_assertion_with_side_effect_method',
  CAA_COVARIANT_ARRAY_FIELD: 'spotbugs.bugDescriptions.caa_covariant_array_field',
  CAA_COVARIANT_ARRAY_RETURN: 'spotbugs.bugDescriptions.caa_covariant_array_return',
  CAA_COVARIANT_ARRAY_LOCAL: 'spotbugs.bugDescriptions.caa_covariant_array_local',
  DMI_UNSUPPORTED_METHOD: 'spotbugs.bugDescriptions.dmi_unsupported_method',
  DMI_THREAD_PASSED_WHERE_RUNNABLE_EXPECTED: 'spotbugs.bugDescriptions.dmi_thread_passed_where_runnable_expected',
  NP_DEREFERENCE_OF_READLINE_VALUE: 'spotbugs.bugDescriptions.np_dereference_of_readline_value',
  NP_IMMEDIATE_DEREFERENCE_OF_READLINE: 'spotbugs.bugDescriptions.np_immediate_dereference_of_readline',
  RV_REM_OF_RANDOM_INT: 'spotbugs.bugDescriptions.rv_rem_of_random_int',
  RV_REM_OF_HASHCODE: 'spotbugs.bugDescriptions.rv_rem_of_hashcode',
  EQ_UNUSUAL: 'spotbugs.bugDescriptions.eq_unusual',
  EQ_DOESNT_OVERRIDE_EQUALS: 'spotbugs.bugDescriptions.eq_doesnt_override_equals',
  NS_NON_SHORT_CIRCUIT: 'spotbugs.bugDescriptions.ns_non_short_circuit',
  NS_DANGEROUS_NON_SHORT_CIRCUIT: 'spotbugs.bugDescriptions.ns_dangerous_non_short_circuit',
  IC_INIT_CIRCULARITY: 'spotbugs.bugDescriptions.ic_init_circularity',
  IA_AMBIGUOUS_INVOCATION_OF_INHERITED_OR_OUTER_METHOD: 'spotbugs.bugDescriptions.ia_ambiguous_invocation_of_inherited_or_outer_method',
  SE_PRIVATE_READ_RESOLVE_NOT_INHERITED: 'spotbugs.bugDescriptions.se_private_read_resolve_not_inherited',
  SE_TRANSIENT_FIELD_OF_NONSERIALIZABLE_CLASS: 'spotbugs.bugDescriptions.se_transient_field_of_nonserializable_class',
  SF_SWITCH_FALLTHROUGH: 'spotbugs.bugDescriptions.sf_switch_fallthrough',
  SF_SWITCH_NO_DEFAULT: 'spotbugs.bugDescriptions.sf_switch_no_default',
  UUF_UNUSED_PUBLIC_OR_PROTECTED_FIELD: 'spotbugs.bugDescriptions.uuf_unused_public_or_protected_field',
  URF_UNREAD_PUBLIC_OR_PROTECTED_FIELD: 'spotbugs.bugDescriptions.urf_unread_public_or_protected_field',
  QF_QUESTIONABLE_FOR_LOOP: 'spotbugs.bugDescriptions.qf_questionable_for_loop',
  NP_UNWRITTEN_PUBLIC_OR_PROTECTED_FIELD: 'spotbugs.bugDescriptions.np_unwritten_public_or_protected_field',
  UWF_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR: 'spotbugs.bugDescriptions.uwf_field_not_initialized_in_constructor',
  UWF_UNWRITTEN_PUBLIC_OR_PROTECTED_FIELD: 'spotbugs.bugDescriptions.uwf_unwritten_public_or_protected_field',
  UC_USELESS_VOID_METHOD: 'spotbugs.bugDescriptions.uc_useless_void_method',
  UC_USELESS_CONDITION: 'spotbugs.bugDescriptions.uc_useless_condition',
  UC_USELESS_CONDITION_TYPE: 'spotbugs.bugDescriptions.uc_useless_condition_type',
  UC_USELESS_OBJECT: 'spotbugs.bugDescriptions.uc_useless_object',
  UC_USELESS_OBJECT_STACK: 'spotbugs.bugDescriptions.uc_useless_object_stack',
  RV_RETURN_VALUE_IGNORED_INFERRED: 'spotbugs.bugDescriptions.rv_return_value_ignored_inferred',
  RV_RETURN_VALUE_IGNORED_NO_SIDE_EFFECT: 'spotbugs.bugDescriptions.rv_return_value_ignored_no_side_effect',
  RV_CHECK_FOR_POSITIVE_INDEXOF: 'spotbugs.bugDescriptions.rv_check_for_positive_indexof',
  RV_DONT_JUST_NULL_CHECK_READLINE: 'spotbugs.bugDescriptions.rv_dont_just_null_check_readline',
  NP_PARAMETER_MUST_BE_NONNULL_BUT_MARKED_AS_NULLABLE: 'spotbugs.bugDescriptions.np_parameter_must_be_nonnull_but_marked_as_nullable',
  NP_NULL_ON_SOME_PATH_FROM_RETURN_VALUE: 'spotbugs.bugDescriptions.np_null_on_some_path_from_return_value',
  NP_NULL_ON_SOME_PATH_MIGHT_BE_INFEASIBLE: 'spotbugs.bugDescriptions.np_null_on_some_path_might_be_infeasible',
  NP_LOAD_OF_KNOWN_NULL_VALUE: 'spotbugs.bugDescriptions.np_load_of_known_null_value',
  PZLA_PREFER_ZERO_LENGTH_ARRAYS: 'spotbugs.bugDescriptions.pzla_prefer_zero_length_arrays',
  UCF_USELESS_CONTROL_FLOW: 'spotbugs.bugDescriptions.ucf_useless_control_flow',
  UCF_USELESS_CONTROL_FLOW_NEXT_LINE: 'spotbugs.bugDescriptions.ucf_useless_control_flow_next_line',
  RCN_REDUNDANT_NULLCHECK_OF_NULL_VALUE: 'spotbugs.bugDescriptions.rcn_redundant_nullcheck_of_null_value',
  RCN_REDUNDANT_NULLCHECK_OF_NONNULL_VALUE: 'spotbugs.bugDescriptions.rcn_redundant_nullcheck_of_nonnull_value',
  RCN_REDUNDANT_COMPARISON_TWO_NULL_VALUES: 'spotbugs.bugDescriptions.rcn_redundant_comparison_two_null_values',
  RCN_REDUNDANT_COMPARISON_OF_NULL_AND_NONNULL_VALUE: 'spotbugs.bugDescriptions.rcn_redundant_comparison_of_null_and_nonnull_value',
  SA_LOCAL_SELF_ASSIGNMENT: 'spotbugs.bugDescriptions.sa_local_self_assignment',
  INT_BAD_REM_BY_1: 'spotbugs.bugDescriptions.int_bad_rem_by_1',
  INT_VACUOUS_COMPARISON: 'spotbugs.bugDescriptions.int_vacuous_comparison',
  INT_VACUOUS_BIT_OPERATION: 'spotbugs.bugDescriptions.int_vacuous_bit_operation',
  SA_LOCAL_DOUBLE_ASSIGNMENT: 'spotbugs.bugDescriptions.sa_local_double_assignment',
  SA_FIELD_DOUBLE_ASSIGNMENT: 'spotbugs.bugDescriptions.sa_field_double_assignment',
  DLS_DEAD_LOCAL_STORE_IN_RETURN: 'spotbugs.bugDescriptions.dls_dead_local_store_in_return',
  DLS_DEAD_LOCAL_STORE: 'spotbugs.bugDescriptions.dls_dead_local_store',
  DLS_DEAD_LOCAL_STORE_SHADOWS_FIELD: 'spotbugs.bugDescriptions.dls_dead_local_store_shadows_field',
  DLS_DEAD_LOCAL_STORE_OF_NULL: 'spotbugs.bugDescriptions.dls_dead_local_store_of_null',
  REC_CATCH_EXCEPTION: 'spotbugs.bugDescriptions.rec_catch_exception',
  DCN_NULLPOINTER_EXCEPTION: 'spotbugs.bugDescriptions.dcn_nullpointer_exception',
  FE_FLOATING_POINT_EQUALITY: 'spotbugs.bugDescriptions.fe_floating_point_equality',
  CD_CIRCULAR_DEPENDENCY: 'spotbugs.bugDescriptions.cd_circular_dependency',
  RI_REDUNDANT_INTERFACES: 'spotbugs.bugDescriptions.ri_redundant_interfaces',
  MTIA_SUSPECT_STRUTS_INSTANCE_FIELD: 'spotbugs.bugDescriptions.mtia_suspect_struts_instance_field',
  MTIA_SUSPECT_SERVLET_INSTANCE_FIELD: 'spotbugs.bugDescriptions.mtia_suspect_servlet_instance_field',
  PS_PUBLIC_SEMAPHORES: 'spotbugs.bugDescriptions.ps_public_semaphores',
  ICAST_INTEGER_MULTIPLY_CAST_TO_LONG: 'spotbugs.bugDescriptions.icast_integer_multiply_cast_to_long',
  ICAST_IDIV_CAST_TO_DOUBLE: 'spotbugs.bugDescriptions.icast_idiv_cast_to_double',
  BC_BAD_CAST_TO_CONCRETE_COLLECTION: 'spotbugs.bugDescriptions.bc_bad_cast_to_concrete_collection',
  BC_UNCONFIRMED_CAST: 'spotbugs.bugDescriptions.bc_unconfirmed_cast',
  BC_UNCONFIRMED_CAST_OF_RETURN_VALUE: 'spotbugs.bugDescriptions.bc_unconfirmed_cast_of_return_value',
  BC_VACUOUS_INSTANCEOF: 'spotbugs.bugDescriptions.bc_vacuous_instanceof',
  BC_BAD_CAST_TO_ABSTRACT_COLLECTION: 'spotbugs.bugDescriptions.bc_bad_cast_to_abstract_collection',
  IM_BAD_CHECK_FOR_ODD: 'spotbugs.bugDescriptions.im_bad_check_for_odd',
  IM_AVERAGE_COMPUTATION_COULD_OVERFLOW: 'spotbugs.bugDescriptions.im_average_computation_could_overflow',
  ICAST_QUESTIONABLE_UNSIGNED_RIGHT_SHIFT: 'spotbugs.bugDescriptions.icast_questionable_unsigned_right_shift',
  DMI_HARDCODED_ABSOLUTE_FILENAME: 'spotbugs.bugDescriptions.dmi_hardcoded_absolute_filename',
  DMI_USELESS_SUBSTRING: 'spotbugs.bugDescriptions.dmi_useless_substring',
  ST_WRITE_TO_STATIC_FROM_INSTANCE_METHOD: 'spotbugs.bugDescriptions.st_write_to_static_from_instance_method',
  DMI_NONSERIALIZABLE_OBJECT_WRITTEN: 'spotbugs.bugDescriptions.dmi_nonserializable_object_written',
  DB_DUPLICATE_BRANCHES: 'spotbugs.bugDescriptions.db_duplicate_branches',
  DB_DUPLICATE_SWITCH_CLAUSES: 'spotbugs.bugDescriptions.db_duplicate_switch_clauses',
  XFB_XML_FACTORY_BYPASS: 'spotbugs.bugDescriptions.xfb_xml_factory_bypass',
  USM_USELESS_SUBCLASS_METHOD: 'spotbugs.bugDescriptions.usm_useless_subclass_method',
  USM_USELESS_ABSTRACT_METHOD: 'spotbugs.bugDescriptions.usm_useless_abstract_method',
  CI_CONFUSED_INHERITANCE: 'spotbugs.bugDescriptions.ci_confused_inheritance',
  TQ_EXPLICIT_UNKNOWN_SOURCE_VALUE_REACHES_NEVER_SINK: 'spotbugs.bugDescriptions.tq_explicit_unknown_source_value_reaches_never_sink',
  TQ_EXPLICIT_UNKNOWN_SOURCE_VALUE_REACHES_ALWAYS_SINK: 'spotbugs.bugDescriptions.tq_explicit_unknown_source_value_reaches_always_sink',
  NP_METHOD_RETURN_RELAXING_ANNOTATION: 'spotbugs.bugDescriptions.np_method_return_relaxing_annotation',
  NP_METHOD_PARAMETER_TIGHTENS_ANNOTATION: 'spotbugs.bugDescriptions.np_method_parameter_tightens_annotation',
  US_USELESS_SUPPRESSION_ON_FIELD: 'spotbugs.bugDescriptions.us_useless_suppression_on_field',
  US_USELESS_SUPPRESSION_ON_CLASS: 'spotbugs.bugDescriptions.us_useless_suppression_on_class',
  US_USELESS_SUPPRESSION_ON_METHOD: 'spotbugs.bugDescriptions.us_useless_suppression_on_method',
  US_USELESS_SUPPRESSION_ON_METHOD_PARAMETER: 'spotbugs.bugDescriptions.us_useless_suppression_on_method_parameter',
  US_USELESS_SUPPRESSION_ON_PACKAGE: 'spotbugs.bugDescriptions.us_useless_suppression_on_package',
}
